version: '3.8'

services:
  web:
    image: php:apache
    volumes:
      - ./your_project:/var/www/html
    ports:
      - "8080:80"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: your_database
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - "8081:80"

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8082:8080"
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  db_data:
  jenkins_home: