version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"  # Map port 80 in the container to port 8080 on the host
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: voting
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./database/voting.sql:/docker-entrypoint-initdb.d/voting.sql  # Mount the SQL file from the database folder

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"  # Map port 80 in the phpMyAdmin container to port 8081 on the host
    environment:
      PMA_HOST: db  # This should match the name of your MySQL service
      PMA_USER: user  # MySQL user
      PMA_PASSWORD: password  # MySQL password
    depends_on:
      - db